### ISSUE TITLE
Progettazione lavori - Analisi dei requisiti

### ISSUE THREAD

**Issue by saniales** [FedericoZorgnotto/vallauri_orari#1]
Salve a tutti

in questo issue vorrei discutere la progettazione iniziale della versione beta del progetto

## Requisiti

Abbiamo capito che è necessaria una fase di raccolta dei requisiti, quindi vorrei da @FedericoZorgnotto (o chi per esso) una lista di funzionalità ad alto livello che ci si aspetta di avere da questo progetto

mi aspetto un elenco puntato di cui ora vado a fare un esempio da cui trarre ispirazione

Per come la vedo io
- Il progetto consiste in un bot telegram che agisce sulla base di comandi
- Abbiamo 2 tipi di utenti (attori) nel sistema: studenti e docenti
- Ci si aspetta che lo studente imposti classe, anno e settore all'interno della scuola
- Ci si aspetta che il docente imposti il suo nome e cognome (dovrebbe esser sufficiente)
- Gli orari vengono parsificati da file PDF locati da qualche parte
- `<finire>`

Buon lavoro

> NOTE: non voglio nomi di prodotti tecnologici menzionati qui (es. usiamo X linguaggio, Y database, libreria Z, etc...) non è ancora il momento di parlarne

**Comment by FedericoZorgnotto** [comment]
noi avevamo pensato a un elenco simile:

- Il progetto consiste in un bot telegram che agisce sulla base di comandi
- Abbiamo 2 tipi di utenti (attori) nel sistema: studenti e docenti
- Ci si aspetta che lo studente imposti classe, anno e settore all'interno della scuola
- Ci si aspetta che il docente imposti il suo nome e cognome (dovrebbe esser sufficiente)
- Gli orari vengono parsificati da file PDF locati da qualche parte
- È possibile modificare il nome delle materie (per esempio nel caso di una modifica da parte dell'insegnante o per un errore (es. italiano/storia))
- È possibile impostare un orario nel quale ottenere l'orario della giornata attuale o successiva
- È possibile ottenere una notifica a ogni cambio di classe o di materia (es. "sei nell'aula T61")

 # Idee marginali 
- sistema di ordinazioni per il bar, in grado di incaricare automaticamente una persona nel gruppo

**Comment by saniales** [comment]
> sistema di ordinazioni per il bar, in grado di incaricare automaticamente una persona nel gruppo

questo lo terrei per buono ma lo skipperei per ora

> È possibile modificare il nome delle materie (per esempio nel caso di una modifica da parte dell'insegnante o per un errore (es. italiano/storia))

questo me lo spieghi?

**Comment by ilgaga809** [comment]
Per esempio: se sull'orario ufficiale si hanno 2 ore di storia consecutive e il professore decide di dedicare una sola ora a storia e l'altra a italiano, vogliamo dare la possibilità di poter cambiare, nell'ora decisa dal docente, la materia in questione.

**Comment by saniales** [comment]
Questa cosa però va concordata dal docente e richiede di operare sul bot su base giornaliera, sicuri ci serva così tanto?

**Comment by FedericoZorgnotto** [comment]
Noi ci avevamo pensato perché per esempio nel nostro orario sono segnate due ore consecutive di storia ma la nostra insegnante ha deciso che fosse più opportuno fare un'ora di italiano e una di storia, pertanto dobbiamo portare entrambi i libri. Se si segue esclusivamente l'orario senza pensare a questo cambiamento si può sbagliare dato che è segnato come due ore di storia, questo obbliga a ricordarsi di questa variazione. Pertanto pensavamo che una cosa simile potesse essere comoda per evitare errori di distrazione quando si prepara lo zaino e per avere un orario che rispecchia effettivamente la realtà.
Altrimenti ci si deve ricordare ogni volta che anche se c'è scritto storia in realtà è un ora di italiano.

**Comment by saniales** [comment]
ok direi che quello che mi serve sapere lo abbiamo, direi che possiamo passare alla fase successiva, ma prima facciamo passare qualche giorno, per vedere se avete altro da aggiungere

**Comment by FedericoZorgnotto** [comment]
Sarebbe interessante fare in modo che le circolari e mail più importanti, come potrebbero essere quelle del preside, vengano girate su telegram dato che solitamente si guardano poco le mail.
Secondo questa logica sarebbe anche interessante ricevere una notifica per i compiti  segnati sul registro, in un modo simile a classroom quando ti ricorda che devi consegnare un compito, ma credo che sia una cosa se non impossibile quantomeno molto complicata dato che si dovrebbero prendere i compiti dal registro.

**Comment by saniales** [comment]
@FedericoZorgnotto per tutte queste funzionalità extra io farei delle milestone separate

Facciamo quello che viene chiamata "roadmap progettuale"

Per fare cio mi serve che abiliti i "projects" su github nelle impostazioni della repository

Io per ora per smuovere il progresso del progetto apro una nuova issue dove iniziamo la pianificazione progettuale della milestone 1

## MIlestone 1: Studenti

- Il progetto consiste in un bot telegram che agisce sulla base di comandi
- Abbiamo 1 tipo di attore nel sistema: studenti
- Ci si aspetta che lo studente imposti classe, anno e settore all'interno della scuola
- Gli orari vengono parsificati da file PDF locati da qualche parte

## Milestone 2: Docenti

- Abbiamo 2 tipi di attori: studenti e docenti
- Ci si aspetta che il docente imposti il suo nome e cognome (dovrebbe esser sufficiente)
- Gli orari **del docente** vengono parsificati da file PDF locati da qualche parte
- È possibile modificare il nome delle materie (per esempio nel caso di una modifica da parte dell'insegnante o per un errore (es. italiano/storia))

## Milestone 3 : Notifiche

- Il progetto consiste in un bot telegram che agisce sulla base di comandi **e imposta promemoria**
- Abbiamo 2 tipi di utenti (attori) nel sistema: studenti e docenti
- È possibile impostare un orario nel quale ottenere l'orario della giornata attuale o successiva
- È possibile ottenere una notifica a ogni cambio di classe o di materia (es. "sei nell'aula T61")
- È possibile aggiungere un promemoria a un'ora o una giornata ricorrenti (per esempio il martedì per l'ora di chimica laboratorio si può aggiungere un promemoria come "ricordati di portare il camice")

Il nuovo task per la milestone 1 lo potete trovare [qui](https://github.com/FedericoZorgnotto/vallauri_orari/issues/3)

**Comment by saniales** [comment]
aggiungo una nota, per la milestone 2 dobbiamo trovare dei prof disposti a farci da tester. Io non basto ce ne servono il piu possibile. 

> **Naturalmente non serve coinvolgerli ora!!!!!** Cerchiamoli quando abbiamo finito la milestone 1
